# Generated by Django 4.1.2 on 2022-10-24 14:00

from django.db import migrations, models
import oauth2discord.managers


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2discord", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="discorduser",
            managers=[("objects", oauth2discord.managers.DiscordUserOauth2Manager()),],
        ),
        migrations.AlterField(
            model_name="discorduser",
            name="last_login",
            field=models.DateTimeField(null=True),
        ),
    ]
